### ISSUE TITLE
全パターンエクスポート機能が動かない

### ISSUE THREAD

**Issue by thr3a** [oov/PSDTool#4]
全パターンをエクスポートをクリックしても0%のままダウンロードができません。

# 環境

- Chrome 110 (safari, Firefoxでも試しましたが変わりませんでした)

# 再現手順

- 「サンプルファイルを試す」をクリック
- 「お気に入り」タブをクリック
- ハンバーガーアイコンより「エクスポート」をクリック
- 「全パターンをエクスポート」をクリック

他のダウンロードは可能でした。デベロッパーツールには特にエラーは表示されておりません。
操作方法が間違っている場合ご教示ください。
（git cloneして以前のコミットを試そうとしましたがnpm installでエラーになってしまい難しい状況です。）

**Comment by oov** [comment]
エクスポートに実装されているのは「全パターンをエクスポート」ではなく「シンプルビューの全パターンをエクスポート」です。
単純な総当りによる全表示パターンのエクスポートは組合せ爆発により処理が完走できない可能性が高いため実装していません。

シンプルビューについては以下のマニュアルを参照してください。
https://oov.github.io/psdtool/manual.html#feature-faview
